version: '3.7'
services:
  connector:
    image: 'docker.pkg.github.com/getnacelle/nacelle-magento-connector/demo-connector:latest'
    container_name: nacelle-magento-connector-poc
    build: .
    environment:
      PORT: 3000
      NODE_ENV: development
      DILITHIUM_HOST: http://index-dilithium-staging.us-east-1.elasticbeanstalk.com/
      DILITHIUM_CLIENT_ID: c85850c8-4366-44e3-a13f-eca27cd6e6a6
      DILITHIUM_TOKEN: ae48665a-318c-45ac-b274-17170bc89d42
      MAGENTO_HOST: http://local.magento/rest/all/V1
      MAGENTO_TOKEN: lc2hu71d72ixgq11tu0iot0752haycvm
    # volumes:
    #   - ~/Sites/nacelle/nacelle-magento-connector:/usr/src/app
    # env_file:
    #   - ./.env
    networks:
      - magento-demo
    depends_on:
      - magento
    ports:
      - 3000:3000
      - 9615:9615
    command: 'pm2-runtime start ./pm2-dev.yml'

  # Magento 2.3 storefront
  magento:
    image: alexcheng/magento2 
    container_name: nacelle-magento-demo
    env_file:
      - ./.env
    volumes:
      - ./theme:/var/www/html/app/design/frontend/nacelle/default
    networks:
      - magento-demo
    depends_on:
      - db
    ports:
      - '80:80'

  # MySQL DB
  db:
    image: mysql:5.6.23
    container_name: nacelle-magento-db
    env_file:
      - ./.env
    volumes:
      - db-data:/var/lib/mysql/data
    networks:
      - magento-demo
    ports:
        - '3306:3306'

  # PHPMyAdmin DB Admin Tool (Optional)
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: nacelle-phpmyadmin
  #   networks:
  #     - magento-demo
  #   depends_on:
  #     - db
  #   ports:
  #     - '8580:80'

volumes:
  db-data:

networks:
  magento-demo:
  